sudo: false
language: php
dist: trusty

php:
  - 7.0

addons:
  chrome: stable

script:
  - google-chrome --headless --disable-web-security --remote-debugging-port=9222  http://127.0.0.1
  - curl -I http://127.0.0.1:9222
